altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  0f1452a5-84ff-4582-b028-f8e91fc9de63:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-07-07T00:19:21+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 2d387b31-d892-4500-9e2f-429153cc5883
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cb24f67e-938d-431c-bfd5-c4ebb30ebf6b
        userCondition: null
    thumbFieldKey: null
fs: images
handle: images
name: Images
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
