defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: d7f69a39-dac3-4926-b8dc-37b3f26c39c6 # Page Builder
handle: print
maxAuthors: 1
minAuthors: 1
name: 'Print Index'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  1a677775-fe98-42e8-be18-ad1606d2fdd0: # Owl Enterprises
    enabledByDefault: true
    hasUrls: true
    template: print/index.twig
    uriFormat: print
type: single
